joy_teleop:
  ros__parameters:
    move:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: /ackermann_cmd
      deadman_buttons: [5]  # hold this to enable drive
      axis_mappings:
        drive-speed:
          axis: 1         # usually left stick vertical
          scale: 2.0      # max speed in m/s
          offset: 0.0
        drive-steering_angle:
          axis: 3         # usually right stick horizontal
          scale: 0.4      # max steering angle in radians
          offset: 0.0
