pure_pursuit:
  ros__parameters:
    waypoints_path: "/home/dev/roboracer_ws/src/pure_pursuit/racelines/porto_track.csv"
    odom_topic: "/car_1/odom"
    car_refFrame: "car_1_base_link"
    global_refFrame: "odom"
    drive_topic: "/ackermann_cmd"
    rviz_current_waypoint_topic: "/current_waypoint"
    rviz_lookahead_waypoint_topic: "/lookahead_waypoint"

    # Pure Pursuit Parameters
    # Lookahead is computed using the following: lookahead = min(max(min_lookahead, max_lookahead * curr_velocity / lookahead_ratio), max_lookahead);
    min_lookahead: 3.5
    max_lookahead: 5.5
    lookahead_ratio: 6.0
    K_p: 0.4
    steering_limit: 45.0
    velocity_percentage: 0.6

waypoint_visualizer_node:
  ros__parameters:
    waypoints_path: "/home/dev/roboracer_ws/src/pure_pursuit/racelines/porto_track.csv"
