<?xml version="1.0"?>
<package format="3">
  <name>roboracer_controller</name>
  <version>0.0.0</version>
  <description>General controller package for roboracer</description>
  <maintainer email="your.email@example.com">loq</maintainer>
  <license>Apache License 2.0</license>

<exec_depend>ros2launch</exec_depend>
<exec_depend>robot_state_publisher</exec_depend>
<exec_depend>xacro</exec_depend>
<exec_depend>controller_manager</exec_depend>  <!-- Keep one instance -->
<exec_depend>rclpy</exec_depend>
<exec_depend>std_msgs</exec_depend>
<exec_depend>geometry_msgs</exec_depend>
<exec_depend>sensor_msgs</exec_depend>
<exec_depend>nav_msgs</exec_depend>
<exec_depend>tf2_ros</exec_depend>
<exec_depend>tf2_msgs</exec_depend>  <!-- Added for TF bridging -->
<exec_depend>ackermann_msgs</exec_depend>  <!-- Added for AckermannDriveStamped -->
<exec_depend>ros_gz_bridge</exec_depend>
<exec_depend>transforms3d</exec_depend>
<depend>python3-urdf-parser-py</depend>

<!-- Optional dependencies -->
<exec_depend>joint_state_publisher</exec_depend>  <!-- Optional for standalone testing -->

<build_depend>python3-pip</build_depend>  <!-- For Python package installation -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>